### ISSUE TITLE
I can't receive another email with the new password.

### ISSUE THREAD

**Issue by pxinwr** [python/psf-infra-meta#105] opened 2021-05-10 06:58 UTC
I tried to reset my password for bpo system as I forgot it. But after I received confirmation email, I can't receive another email with the new password. Any problem with the Python login system?

**Comment by matrixise** [comment] 2021-05-10 07:49
Hi @pxinwr 

I have checked with the same procedure, "Lost your login?" and I have received two emails as you can check with my screenshot. No problem with the Python login system. off chance, have you checked your SPAM folder?

<img width="838" alt="Screenshot 2021-05-10 at 09 46 38" src="https://user-images.githubusercontent.com/38737/117623927-a7889180-b174-11eb-83ff-4dc6aeb8dd6c.png">

I am going to close this issue because I can't reproduce it. 

Re-open it gain if you still have it.

**Closed as completed by matrixise** 2021-05-10 07:49 UTC

**Comment by pxinwr** [comment] 2021-05-10 09:09
Thanks @matrixise Not in my spam folder. However, now I can successfully login in using my associated github account. Also setting new password succeeds. Let's skip the issue since I've got solution.
